In [44]:
import numpy as np

In [45]:
arr_list = np.array([52, 67, 76, 44, 322])
print("Массив из списка:", arr_list)

Массив из списка: [ 52  67  76  44 322]


In [46]:
arr_zeros = np.zeros((2, 2))
print("Массив из нулей:\n", arr_zeros)

Массив из нулей:
 [[0. 0.]
 [0. 0.]]


In [47]:
arr_ones = np.ones((3, 3))
print("Массив из единиц:\n", arr_ones)

Массив из единиц:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
arr_arange = np.arange(0, 10, 2)
print("Массив с помощью arange:", arr_arange)

Массив с помощью arange: [0 2 4 6 8]


In [49]:
print("Форма массива arr_ones:", arr_ones.shape)
print("Тип данных массива arr_ones:", arr_ones.dtype)

Форма массива arr_ones: (3, 3)
Тип данных массива arr_ones: float64


In [50]:
element = arr_list[1] 
print("Второй элемент массива arr_list:", element)


Второй элемент массива arr_list: 67


In [51]:
sub_array = arr_list[0:2]
print("Подмассив arr_list[0:2] (0 и 1 элементы):", sub_array)

Подмассив arr_list[0:2] (0 и 1 элементы): [52 67]


In [52]:
arr_sum = arr_list + arr_arange
print("Сумма двух массивов arr_list и arr_arange: ", arr_sum)

Сумма двух массивов arr_list и arr_arange:  [ 52  69  80  50 330]


In [53]:
arr_sum_5 = arr_list + 5
print("Поэлементное сложение arr_list и 5: ", arr_sum_5)

Поэлементное сложение arr_list и 5:  [ 57  72  81  49 327]


In [54]:
arr_prod = arr_list * arr_arange
print("Поэлементное умножение двух массивов arr_list и arr_arange:", arr_prod)

Поэлементное умножение двух массивов arr_list и arr_arange: [   0  134  304  264 2576]


In [55]:
arr_prod_3 = arr_list * 3
print("Поэлементное умножение массива arr_list и 3:", arr_prod_3)

Поэлементное умножение массива arr_list и 3: [156 201 228 132 966]


In [56]:
mean_value = arr_list.mean()
print("Среднее значение массива arr_list:", mean_value)

Среднее значение массива arr_list: 112.2


In [57]:
sum_value = arr_list.sum()
print("Сумма элементов массива arr_list:", sum_value)

Сумма элементов массива arr_list: 561
